# concurrencies: 1126
prefill:
  num: 8
  config:
    max_batch_size: 2
    max_num_tokens: 16640
    max_seq_len: 8232
    tensor_parallel_size: 2
    moe_expert_parallel_size: 2
    enable_attention_dp: true
    pipeline_parallel_size: 1
    print_iter_log: true
    cuda_graph_config: null
    disable_overlap_scheduler: true
    moe_config:
      backend: TRTLLM
    kv_cache_config:
      enable_block_reuse: false
      free_gpu_memory_fraction: 0.6
      dtype: fp8
    cache_transceiver_config:
      max_tokens_in_buffer: 16384
      backend: UCX
  env:
    TRTLLM_SERVER_DISABLE_GC: 1
    TRTLLM_WORKER_DISABLE_GC: 1
    NCCL_GRAPH_MIXING_SUPPORT: 0
    TRTLLM_ENABLE_PDL: 1
  unset_env:
    - UCX_TLS
decode:
  num: 1
  config:
    tensor_parallel_size: 16
    moe_expert_parallel_size: 16
    enable_attention_dp: true
    enable_lm_head_tp_in_adp: false
    pipeline_parallel_size: 1
    max_batch_size: 64
    max_num_tokens: 64
    max_seq_len: 9256
    cuda_graph_config:
      enable_padding: true
      batch_sizes:
      - 1
      - 2
      - 4
      - 8
      - 16
      - 24
      - 32
      - 40
      - 48
      - 56
      - 64
    print_iter_log: true
    kv_cache_config:
      enable_block_reuse: false
      free_gpu_memory_fraction: 0.8
      dtype: fp8
    moe_config:
      backend: CUTEDSL
      use_low_precision_moe_combine: true
    cache_transceiver_config:
      max_tokens_in_buffer: 16384
      backend: UCX
    stream_interval: 100
    num_postprocess_workers: 4
  env:
    TRTLLM_SERVER_DISABLE_GC: 1
    TRTLLM_WORKER_DISABLE_GC: 1
    NCCL_GRAPH_MIXING_SUPPORT: 0
    TRTLLM_ENABLE_PDL: 1
  unset_env:
    - UCX_TLS

