# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: nvidia.com/v1alpha1
kind: DynamoModel
metadata:
  name: chhagan-docvl-qwen
spec:
  modelName: Chhagan005/Chhagan-DocVL-Qwen3
  baseModelName: Qwen/Qwen3-VL-2B-Instruct
  modelType: lora
  source:
    uri: s3://my-loras/Chhagan005/Chhagan-DocVL-Qwen3