# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: vllm-agg-routellm
spec:
  services:
    RouteLLMProxy:
      dynamoNamespace: vllm-agg-routellm
      componentType: proxy
      replicas: 1
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:my-tag
          command:
          - python3
          - -m
          - dynamo.nemo_switchyard
          args:
            - --http-port
            - "8080"
            - --backend-url
            - http://frontend:8000
            - --strong-model
            - Qwen/Qwen3-4B
            - --weak-model
            - Qwen/Qwen3-0.6B
            - --router-type
            - mf
            - --threshold
            - "0.5"
    Frontend:
      dynamoNamespace: vllm-agg-routellm
      componentType: frontend
      replicas: 1
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:my-tag
    VllmStrongWorker:
      envFromSecret: hf-token-secret
      dynamoNamespace: vllm-agg-routellm
      componentType: worker
      replicas: 1
      resources:
        limits:
          gpu: "1"
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:my-tag
          workingDir: /workspace/components/backends/vllm
          command:
          - python3
          - -m
          - dynamo.vllm
          args:
            - --model
            - Qwen/Qwen3-4B
    VllmWeakWorker:
      envFromSecret: hf-token-secret
      dynamoNamespace: vllm-agg-routellm
      componentType: worker
      replicas: 1
      resources:
        limits:
          gpu: "1"
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:my-tag
          workingDir: /workspace/components/backends/vllm
          command:
          - python3
          - -m
          - dynamo.vllm
          args:
            - --model
            - Qwen/Qwen3-0.6B
