apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nvidia.com_dynamocheckpoints.yaml
  - nvidia.com_dynamocomponentdeployments.yaml
  - nvidia.com_dynamographdeploymentrequests.yaml
  - nvidia.com_dynamographdeployments.yaml
  - nvidia.com_dynamographdeploymentscalingadapters.yaml
  - nvidia.com_dynamomodels.yaml
  - nvidia.com_dynamoworkermetadatas.yaml
